#
# Docker compose file
# EPITECH 2019 - CashManager
#

version : '3'
services:
    api:
        container_name: cashmanager_api
        command:
            - ./api/entrypoint.sh
        build:
            context: ./apps/products
        environment:
            PGUSER: postgres
            PGPASSWORD: postgres
            PGDATABASE: cashmanager
            PGPORT: 5432
            PGHOST: db
        ports:
          - "9090:9090"
        depends_on:
            db
    db:
        container_name: cashmanager_db
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        volumes:
            - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
            - "dbdata:/var/lib/postgresql/data"
volumes:
    dbdata:
