#
# Docker compose file
# EPITECH 2019 - CashManager
#

version : '3'
services:
    client:
        container_name: cashmanager_client
        image: berthieresteban/cashmanager_client
        build: 
            context: ./apps/mobile
        ports:
            - "8081:8081"

    api:
        container_name: cashmanager_api
        image: berthieresteban/cashmanager_api
        build:
            context: ./apps/products
        ports:
          - "8080:8080"
        depends_on:
            [db]
    db:
        container_name: cashmanager_db
        build: 
            context: ./db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/cashmanager
        restart: always